package br.org.mosaic.properties;

/** A set of Styles names
 * @author andrew */
public enum StyleName {

	BACKGROUND				( "background" ),
	BACKGROUND_ATTACHMENT	( "background-attachment" ),
	BACKGROUND_COLOR		( "background-color" ),
	BACKGROUND_IMAGE		( "background-image" ),
	BACKGROUND_POSITION		( "background-position" ),
	BACKGROUND_REPEAT		( "background-repeat" ),
	BORDER					( "border" ),
	BORDER_BOTTOM			( "border-bottom" ),
	BORDER_BOTTOM_COLOR		( "border-bottom-color" ),
	BORDER_BOTTOM_STYLE		( "border-bottom-style" ),
	BORDER_BOTTOM_WIDTH		( "border-bottom-width" ),
	BORDER_COLOR			( "border-color" ),
	BORDER_COLLAPSE			( "border-collapse" ),
	BORDER_LEFT				( "border-left" ),
	BORDER_LEFT_COLOR		( "border-left-color" ),
	BORDER_LEFT_STYLE		( "border-left-style" ),
	BORDER_LEFT_WIDTH		( "border-left-width" ),
	BORDER_RIGHT			( "border-right" ),
	BORDER_RIGHT_COLOR		( "border-right-color" ),
	BORDER_RIGHT_STYLE		( "border-right-style" ),
	BORDER_RIGHT_WIDTH		( "border-right-width" ),
	BORDER_SPACING			( "border-spacing" ),
	BORDER_STYLE			( "border-style" ),
	BORDER_TOP				( "border-top" ),
	BORDER_TOP_COLOR		( "border-top-color" ),
	BORDER_TOP_STYLE		( "border-top-style" ),
	BORDER_TOP_WIDTH		( "border-top-width" ),
	BORDER_WIDTH			( "border-width" ),
	BOTTOM					( "bottom" ),
	CAPTION_SIDE			( "caption-side" ),
	CLEAR					( "clear" ),
	CLIP					( "clip" ),
	COLOR					( "color" ),
	CONTENT					( "content" ),
	COUNTER_INCREMENT		( "counter-increment" ),
	COUNTER_RESET			( "counter-reset" ),
	CURSOR					( "cursor" ),
	DIRECTION				( "direction" ),
	DISPLAY					( "display" ),
	EMPTY_CELLS				( "empty-cells" ),
	FLOAT					( "float" ),
	FONT					( "font" ),
	FONT_FAMILY				( "font-family" ),
	FONT_SIZE				( "font-size" ),
	FONT_STYLE				( "font-style" ),
	FONT_VARIANT			( "font-variant" ),
	FONT_WEIGHT				( "font-weight" ),
	HEIGHT					( "height" ),
	LEFT					( "left" ),
	LETTER_SPACING			( "letter-spacing" ),
	LINE_HEIGHT				( "line-height" ),
	LIST_STYLE				( "list-style" ),
	LIST_STYLE_IMAGE		( "list-style-image" ),
	LIST_STYLE_POSITION		( "list-style-position" ),
	LIST_STYLE_TYPE			( "list-style-type" ),
	MARGIN					( "margin" ),
	MARGIN_BOTTOM			( "margin-bottom" ),
	MARGIN_LEFT				( "margin-left" ),
	MARGIN_RIGHT			( "margin-right" ),
	MARGIN_TOP				( "margin-top" ),
	MAX_HEIGHT				( "max-height" ),
	MAX_WIDTH				( "max-width" ),
	MIN_HEIGHT				( "min-height" ),
	MIN_WIDTH				( "min-width" ),
	ORPHANS					( "orphans" ),
	OUTLINE					( "outline" ),
	OUTLINE_COLOR			( "outline-color" ),
	OUTLINE_STYLE			( "outline-style" ),
	OUTLINE_WIDTH			( "outline-width" ),
	OVERFLOW				( "overflow" ),
	PADDING					( "padding" ),
	PADDING_BOTTOM			( "padding-bottom" ),
	PADDING_LEFT			( "padding-left" ),
	PADDING_RIGHT			( "padding-right" ),
	PADDING_TOP				( "padding-top" ),
	PAGE_BREAK_AFTER		( "page-break-after" ),
	PAGE_BREAK_BEFORE		( "page-break-before" ),
	PAGE_BREAK_INSIDE		( "page-break-inside" ),
	POSITION				( "position" ),
	QUOTES					( "quotes" ),
	RIGHT					( "right" ),
	TABLE_LAYOUT			( "table-layout" ),
	TEXT_ALIGN				( "text-align" ),
	TEXT_DECORATION			( "text-decoration" ),
	TEXT_INDENT				( "text-indent" ),
	TEXT_SHADOW				( "text-shadow" ),
	TEXT_TRANSFORM			( "text-transform" ),
	TOP						( "top" ),
	UNICODE_BIDI			( "unicode-bidi" ),
	VERTICAL_ALIGN			( "vertical-align" ),
	VISIBILITY				( "visibility" ),
	WHITE_SPACE				( "white-space" ),
	WIDOWS					( "widows" ),
	WIDTH					( "width" ),
	WORD_SPACING			( "word-spacing" ),
	Z_INDEX					( "z-index" )
	;
	
	private String name;
	
	private StyleName(String name) {
	}
	
	public String getName() {
		return name;
	}
}